export const gradients = [
  "bg-gradient-to-tl from-cyan-300 via-blue-500 to-purple-600",
  "bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500",
  "bg-gradient-to-r from-green-400 to-blue-500",
  "bg-gradient-to-r from-purple-400 to-pink-500",
  "bg-gradient-to-r from-green-300 via-blue-500 to-purple-600",
  "bg-gradient-to-r from-gray-700 via-gray-900 to-black",
  "bg-gradient-to-r from-green-400 via-green-400 to-purple-700",
  "bg-gradient-to-r from-red-400 to-red-600",
  "bg-gradient-to-r from-purple-400 via-purple-400 to-purple-800",
  "bg-gradient-to-r from-purple-700 to-amber-500",
  "bg-gradient-to-r from-red-600 via-yellow-600 to-yellow-500",
  "bg-gradient-to-r from-blue-700 via-blue-800 to-gray-900",
  "bg-gradient-to-r from-yellow-600 to-red-600",
  "bg-gradient-to-r from-slate-900 via-purple-900 to-slate-900",
  "bg-gradient-to-bl from-indigo-900 via-indigo-400 to-indigo-900",
  "bg-gradient-to-b from-gray-900 via-purple-900 to-violet-600",
  "bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-amber-700 via-orange-500 to-rose-800",
  "bg-[radial-gradient(ellipse_at_bottom,_var(--tw-gradient-stops))] from-amber-400 via-violet-600 to-sky-900",
  "bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-gray-300 via-fuchsia-600 to-orange-600",
  "bg-gradient-to-r from-lime-600 via-amber-500 to-red-600",
  "bg-gradient-to-b from-orange-500 to-yellow-300",
  "bg-gradient-to-r from-fuchsia-500 via-red-600 to-orange-400",
  "bg-gradient-to-r from-emerald-500 to-lime-600",
  "bg-[conic-gradient(at_left,_var(--tw-gradient-stops))] from-yellow-500 via-purple-500 to-blue-500",
  "bg-gradient-to-tl from-slate-700 to-sky-600",
  "bg-gradient-to-r from-fuchsia-400 to-violet-500",
  "bg-gradient-to-r from-lime-500 to-emerald-500",
  "bg-gradient-to-r from-purple-500 to-rose-500",
  "bg-gradient-to-r from-sky-500 to-rose-500",
  "bg-gradient-to-r from-rose-500 to-fuchsia-500",
  "bg-gradient-to-r from-amber-500 to-red-500",
  "bg-gradient-to-r from-cyan-500 to-sky-500",
  "bg-gradient-to-r from-fuchsia-500 to-rose-500",
];

export const prompts = [
  "What is your favorite color?🎨",
  "What is your favorite food?🍕",
  "What is your favorite pickup line?😏",
  "I have a crush on you 🥺👉🏻👈🏻",
  "What is your favorite movie?🎥",
  "Coffee date sometime?☕️🥰",
  "Can we be friends?🥰😁",
  "Are you a parking ticket? Because you’ve got fine written all over you.✨",
  "I’m not a photographer, but I can picture us together.📸",
  "Do you have a map? I’m getting lost in your eyes.️",
  "If you were a vegetable, you’d be a cute-cumber.😚",
  "Do you have a name or can I call you mine?🥰",
  "Are you a magician? Because whenever I look at you, everyone else disappears.🪄",
  "You are cute.",
  "We need to talk (more🤪)! ",
  "I like your smile😍",
  "The only bad thing about you😒 is that you’re not mine yet.🤭",
  "you are really a great friend🥰",
  "You are so beautiful that you made me forget my pickup line.😳",
  "Is your name Google? Because you have everything I’m searching for.",
  "I’m not a photographer, but I can picture us together.",
  "Are you a magician? Because whenever I look at you, everyone else disappears.",
  "I was wondering if you had an extra heart. Mine was just stolen.",
  "I must be a snowflake, because I’ve fallen for you.❄️",
  "Do you believe in love at first sight—or should I walk by again?",
  "Kiss me if I’m wrong, but dinosaurs still exist, right?",
  "I’m lost. Can you give me directions to your heart?",
  "I’m learning about important dates in history. Wanna be in one of them?️",
  "Who is your celebrity crush?",
  "If we were superheroes, what would our powers be?",
  "What's a dream you've been putting off?",
  "What brings you the most joy in life?",
  "If you could change one thing about the world, what would it be?",
  "What's the craziest thing you've ever done?",
  "What's your biggest fear?",
  "Tell me about a time you overcame a challenge.",
  "What makes you laugh the most?",
  "What's one thing you've always wanted to try?",
  "What's your favorite thing about yourself?",
];
